"""Object storage interface. Keys are generated by the server, never taken from user input."""

from collections.abc import Iterable
from typing import BinaryIO, Protocol


class ObjectStorage(Protocol):
    def put(self, key: str, chunks: Iterable[bytes]) -> None:
        """Stores the chunks under key. Either the whole object exists afterwards or none of it."""

    def open(self, key: str) -> BinaryIO:
        """Opens the object for reading. Raises FileNotFoundError if it does not exist."""

    def delete(self, key: str) -> None:
        """Removes the object. Does nothing if it does not exist."""

    def exists(self, key: str) -> bool: ...
